name: 'R2 Backup'
author: 'Jose Moran Urena'
description: 'Mirror a repository to a Cloudflare R2 bucket'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'  
  color: 'orange'
